=== bittebak/xmlxslt/xsd-1/PurchaseOrder.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2019 rel. 3 (x64) (http://www.altova.com) by Mr Me (YT) -->
<xs:schema xmlns:yt="http://www.yellowtwig.nl/training/xmlxslt" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" targetNamespace="http://www.yellowtwig.nl/training/xmlxslt" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:complexType name="PurchaseOrderType">
		<xs:sequence>
			<xs:element name="CreatedOn" type="xs:date"/>
			<xs:element name="OrderLines" maxOccurs="10">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="OrderLine">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="ProductName"/>
									<xs:element name="Quantity" type="xs:positiveInteger"/>
									<xs:element name="Price" type="xs:decimal"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Priority">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Standard"/>
						<xs:enumeration value="NextDay"/>
						<xs:enumeration value="SameDay"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="PurchaseOrder" type="yt:PurchaseOrderType"/>
</xs:schema>

=== bittebak/xmlxslt/xsd-1/purchaseorder-generated.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2019 rel. 3 (x64) (http://www.altova.com)-->
<yt:PurchaseOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:yt="http://www.yellowtwig.nl/training/xmlxslt" xsi:schemaLocation="http://www.yellowtwig.nl/training/xmlxslt PurchaseOrder.xsd">
	<yt:CreatedOn>1957-08-13</yt:CreatedOn>
	<yt:OrderLines>
		<yt:OrderLine>
			<yt:ProductName>text</yt:ProductName>
			<yt:Quantity>2</yt:Quantity>
			<yt:Price>0</yt:Price>
		</yt:OrderLine>
	</yt:OrderLines>
	<yt:OrderLines>
		<yt:OrderLine>
			<yt:ProductName>text</yt:ProductName>
			<yt:Quantity>2</yt:Quantity>
			<yt:Price>0</yt:Price>
		</yt:OrderLine>
	</yt:OrderLines>
	<yt:OrderLines>
		<yt:OrderLine>
			<yt:ProductName>text</yt:ProductName>
			<yt:Quantity>2</yt:Quantity>
			<yt:Price>0</yt:Price>
		</yt:OrderLine>
	</yt:OrderLines>
	<yt:Priority>Standard</yt:Priority>
</yt:PurchaseOrder>
